declare interface ObjectiveViewDto {
    /**
     * The unique identifier of the objective. This is a read-only property. It
     * will be automatically generated by the server. The client will not be able
     * to set this value. Usually, this is the primary key of the objective in the
     * database.
     */
    readonly id: number;

    /**
     * The name of the objective.
     */
    name: string;

    description: string;

    userId: string;

    idpId: number;
    
    category: any;

    status: number;

    startDate: Date;

    endDate: Date;
}
